### PR TITLE
Use add_js instead of add_javascript

### LINKED ISSUE #58: Support Sphinx 3
```
Running Sphinx v3.0.0b1
c:\users\dalton smith\appdata\local\programs\python\python37-32\lib\site-packages\sphinx_tabs\tabs.py:341: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
  app.add_javascript(path)
```

### PR DESCRIPTION
**Pull request by Daltz333**
Closes #58

### CODE REVIEW

**Comment by Daltz333** [comment]
@djungelorm any objections?

**Comment by dirk-thomas** [comment]
It would be great to get this fix released.

**Comment by mjcarroll** [comment]
@djungelorm friendly ping.

**Comment by ScriptAutomate** [comment]
This would be great to get accepted and pushed to PyPI, as I'm otherwise getting a warning message with Sphinx 3.0.x when using this extension due to the deprecation.

**Comment by mjcarroll** [comment]
@djungelorm Friendly ping :bell:

**Comment by webknjaz** [comment]
@djungelorm mind merging?

**Comment by return42** [comment]
@djungelorm sorry for being impatient / can you please merge this PR / thanks!!!

**Comment by ravindk89** [comment]
In the short term y'all can fork and make the fix locally. It's a bit of a pain, but its better than nothing. I have https://github.com/ravindk89/sphinx-tabs open, and pull it in via requirements.txt as git+https://github.com/ravindk89/sphinx-tabs

**Comment by return42** [comment]
> In the short term y'all can fork and make the fix locally

For those of use who won't like to fork on github (on a remote); you can pull PRs locally:

    git clone https://github.com/djungelorm/sphinx-tabs
    git pull origin refs/pull/59/head

>  and pull it in via requirements.txt 

Remote or (local) "forks" are not the solution for the community ([670+ are using sphinx-tab on github](https://github.com/djungelorm/sphinx-tabs/network/dependents?package_id=UGFja2FnZS01MjYwNTUyNQ%3D%3D) + x unknown users [e.g. from pypi](https://pypi.org/project/sphinx-tabs/#history)).

> I have https://github.com/ravindk89/sphinx-tabs open

Thanks for the offer .. to me it seems that the maintainer is absence for a longer time .. do you interested to maintain a fork?  If so we can send our PRs to your fork.  But this won't solve the pypi problem :(

If someone is willing to maintain a fork, I will support him .. if there comes the day @djungelorm  comes back to github, we can merge the fork back to @djungelorm 's origin

**Comment by Daltz333** [comment]
My organization was interested in maintaintainig a fork for a brief period, see https://github.com/wpilibsuite/sphinxext-tabs, but we started developing a couple of other extensions in the meantime.

**Comment by ravindk89** [comment]
I'm sadly still very new to Sphinx Extensions, so at most I'd be happy to accept PRs from others to my fork if something comes up, but I'm not in a position (yet?) to review for correctness.

**Comment by Daltz333** [comment]
The repository has been moved to the executablebooks github organization, and this issue has been closed. As I screwed up my original fork. A new PR has been created #77 which also includes some backwards compatibility so we don't break users using Sphinx < 3

**Pull request closed without merging**
