### PR TITLE
🧪 TESTS: Add testing for Python 3.9 and pygments versions

### PR DESCRIPTION
**Pull request by foster999**
Adds tesing for:
* Python version 3.9
* a range of `pygments` versions, in response to #134
* latest `sphinx` version above 4 (was previously fixed to `==4.0.0b1`)

### CODE REVIEW

**Comment by foster999** [comment]
Hi @humitos, I've just realised that the new test using ` app.set_html_assets_policy("always")` wasn't getting hit because our `sphinx` testing version was fixed below 4.1 😅 

I've changed that here to test the latest between 4 and 5, and the new test is now failing. It looks like the JS asset isn't being included when the config option is set. I'm stuck on why this might be, any thoughts?

**Comment by humitos** [comment]
> Hi @humitos, I've just realised that the new test using ` app.set_html_assets_policy("always")` wasn't getting hit because our `sphinx` testing version was fixed below 4.1 sweat_smile

I remember running the test and failing locally. Then, after some debugging, I was able to fix it (see this comment https://github.com/executablebooks/sphinx-tabs/pull/127#discussion_r675979667 where we talked about this failing test)

I'm not sure how the .html/.xml files added to this PR were generated (I didn't upload them in my original PR). So, I'm guessing there is something there that may be conflicting. I'll take a look next week.

**Comment by foster999** [comment]
Thanks, I'd totally forgotten about that. Working fine with a copy of the test source files now 😄

**Comment by humitos** [comment]
Excellent! Happy you already fixed it! 💪

**Pull request merged**
