### PR TITLE
Make Tabs collapsible

### PR DESCRIPTION
**Pull request by HaSa1002**
Collapse

### CODE REVIEW

**Comment by akien-mga** [comment]
Is there any interest in this PR? We want to use it for https://github.com/godotengine/godot-docs and would prefer not to have to maintain a fork with custom changes if we can avoid it.

**Comment by foster999** [comment]
Hey @akien-mga and @HaSa1002, the latest release (v2.0.0) includes a rewrite of the extension's JS. I've included an equivalent to this improvement in that release, please could you let me know if it works as expected?

**Comment by HaSa1002** [comment]
@foster999 I did a quick build of said repo and it appears to work fine.

**Comment by foster999** [comment]
Great, thanks for checking!

**Pull request closed without merging**
