### PR TITLE
Fix hiding tabs

### LINKED ISSUE #105: Tabs disappearing after being clicked
**Describe the bug**

In 2.0.1 (after #101) we can (again) place images and more in tabs. However, the tabs behave badly if we stress test them by spam clicking on them for a while. In particular, all tabs except the left-most one disappears. I then have to reload the page for the other tabs to become visible again.

**To Reproduce**

I'm not sure if the images are in fact related to the problem, but I only see this behavior for the tabs in which I include images and math. The RST I use is in #101. I've [uploaded](https://github.com/executablebooks/sphinx-tabs/files/5947017/tabs.zip) the resulting HTML: Scroll down a bit and you see the tabs "Linux", "Windows", "macOS" and "Docker". Try spam clicking them, e.g. 5 times fast on "Linux", then once on "Windows", then once on "macOS", then 5 times on "Docker". For me, the bug appears like 4/5 times by doing so (and when not I just spam a little more).

**Environment**

- Python 3.9.0
- sphinx-tabs 2.0.1
- Linux Mint 20
- Google Chrome and Firefox (bug appears about equally often in both).

### PR DESCRIPTION
**Pull request by foster999**
Changes:
* Fix JS to stop tabs disappearing when elements nested inside the button are clicked.
* Add outline offset when tabs are focused to prevent resizing when changing tab.

Closes #105

### CODE REVIEW

**Comment by Daltz333** [comment]
Should a test get verified that a tab gets hidden and unhidden properly?

**Comment by foster999** [comment]
Yeah, we don't have any JS tests so this might be a good opportunity to get at least one in... Any experience with writing tests for JS? I'm yet to give it a try.

Also, looks like `pygments` has changed something so one of the regression tests is failing. Shall check if that affects appearance in any way.

**Comment by foster999** [comment]
My attempt at testing the simplest function in the module is failing. Not sure if you have experience testing JS using `jest` @Daltz333?

I must be using this incorrectly, as the `selectTab` function has no effect on the button or panel:
```js
const tabs = require('../tabs')

describe("Selecting a tab", () => {
    test("tab become selected", () => {
        // Set up our document body
        document.body.innerHTML =
        '<div>' +
        '  <button id="test-button" aria-controls="panel-id" aria-selected="false">Test</button>' +
        '  <div id="panel-id" hidden="true">Test</div>' +
        '</div>';

        let button = document.getElementById('test-button');
        let panel = document.getElementById('panel-id');
        expect(button.getAttribute('aria-selected')).toEqual('false')
        expect(panel.getAttribute('hidden')).toEqual("true")

        tabs.selectTab(button)

        expect(button.getAttribute('aria-selected')).toEqual('true')
        expect(panel.getAttribute('hidden')).toEqual("false")
    })
})

```

**Comment by Daltz333** [comment]
I'm not familiar with Javascript beyond a basic extent. Mostly a python developer and documentation writer myself. If tests are blocking, we can always merge now and test properly later.

**Comment by foster999** [comment]
Same here to be honest 😅 yeah that's fair, I'll ask a friend about the testing and get it in later.

Are you happy with the changes in this PR (fix has been verified by those who raised the issue) and #107?

**Pull request merged**
