### PR TITLE
⬆️ UPGRADE: Bump docutils dependency to 0.17

### LINKED ISSUE #140: Tests fail with docutils 0.17.1 on Fedora Rawhide
### Describe the problem

The following tests fail when building with docutils 0.17.1.
```
FAILED tests/test_build.py::test_conditional_assets_html_assets_policy[index]
FAILED tests/test_build.py::test_conditional_assets_html_assets_policy[no_tabs1]
FAILED tests/test_build.py::test_conditional_assets_html_assets_policy[no_tabs2]
```

### Link to your repository or website

https://bugzilla.redhat.com/show_bug.cgi?id=2005976

### Steps to reproduce

1. Update docutils from 0.16 to 0.17.1
2. Attempt package rebuild
3. pytest produces failed tests.

### The version of Python you're using

3.10

### Your operating system

Fedora Rawhide x86_64

### Versions of your packages

```
python-setuptools-wheel-57.4.0-1.fc35.noarch
python-pip-wheel-21.2.3-2.fc36.noarch
python3-3.10.0~rc2-2.fc36.x86_64
python3-libs-3.10.0~rc2-2.fc36.x86_64
python3-setuptools-57.4.0-1.fc35.noarch
python3-idna-3.2-1.fc35.noarch
python3-py-1.10.0-5.fc35.noarch
python3-attrs-21.2.0-4.fc35.noarch
python3-charset-normalizer-2.0.6-1.fc36.noarch
python3-imagesize-1.2.0-6.fc35.noarch
python3-iniconfig-1.1.1-5.fc35.noarch
python3-markupsafe-2.0.0-2.fc35.x86_64
python3-pluggy-1.0.0-1.fc36.noarch
python3-pygments-2.10.0-1.fc36.noarch
python3-pyparsing-2.4.7-9.fc35.noarch
python3-packaging-21.0-2.fc35.noarch
python3-rpm-generators-12-8.fc35.noarch
python3-pysocks-1.7.1-11.fc35.noarch
python3-pytz-2021.1-4.fc35.noarch
python3-babel-2.9.1-4.fc35.noarch
python3-jinja2-3.0.1-2.fc35.noarch
python3-pyyaml-5.4.1-4.fc35.x86_64
python3-six-1.16.0-4.fc35.noarch
python3-urllib3-1.26.6-2.fc35.noarch
python3-requests-2.26.0-1.fc35.noarch
python3-snowballstemmer-1.9.0-10.fc35.noarch
python3-soupsieve-2.2.1-2.fc35.noarch
python3-lxml-4.6.3-4.fc35.x86_64
python3-beautifulsoup4-4.10.0-1.fc36.noarch
python3-sphinx-theme-alabaster-0.7.12-13.fc35.noarch
python3-sphinxcontrib-applehelp-1.0.2-6.fc35.noarch
python3-sphinxcontrib-devhelp-1.0.2-6.fc35.noarch
python3-sphinxcontrib-htmlhelp-2.0.0-2.fc35.noarch
python3-sphinxcontrib-jsmath-1.0.1-13.fc35.noarch
python3-sphinxcontrib-qthelp-1.0.3-6.fc35.noarch
python3-sphinxcontrib-serializinghtml-1.1.5-2.fc35.noarch
python3-toml-0.10.2-5.fc35.noarch
python3-pytest-6.2.5-1.fc36.noarch
python3-pytest-datadir-1.3.1-1.fc35.noarch
python3-docutils-0.17.1-1.fc36.noarch
python3-sphinx-4.2.0-1.fc36.noarch
python3-pytest-regressions-2.2.0-1.fc35.noarch
python3-devel-3.10.0~rc2-2.fc36.x86_64
python3-wheel-0.37.0-1.fc36.noarch
python3-pip-21.2.3-2.fc36.noarch
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by foster999**
Regression tests updated, as the new version now uses semantic `section` tags rather than the class of the same name.

Fixes #140

### CODE REVIEW

**Comment by foster999** [comment]
@Daltz333, any thoughts on upgrading to docutils~=0.17.0? 

As there doesn't seem to include any functional changes for us, we can continue to support 0.16. Should this then be something like `docutils~=0.16.0,~=0.17.0`?

**Comment by Daltz333** [comment]
Since RTD theme added support for 0.17 and tests pass, it should be fine

**Comment by Daltz333** [comment]
I can push a release later today if he doesn't beat me to it.

**Comment by return42** [comment]
> I can push a release later today if he doesn't beat me to it.

Sorry for being impatient .. just to remind / Thanks!

**Comment by foster999** [comment]
> 
> Sorry for being impatient .. just to remind / Thanks!

Thanks for nudging again - should be available at a `pip` near you!

**Comment by return42** [comment]
> should be available at a `pip` near you!

Thanks a lot .. great help for me!

**Pull request merged**
