### PR TITLE
Make the tests pass with Sphinx 7.1

### PR DESCRIPTION
**Pull request by mitya57**
The tests were failing with this diff:
```diff
-<document source="index.rst">
+<document source="index.rst" translation_progress="{'total': 0, 'translated': 0}">
```

See https://bugs.debian.org/1042589 for the full log.

This was caused by sphinx-doc/sphinx#11509, which is part of Sphinx ≥ 7.1.0.

### CODE REVIEW

**Comment by foster999** [comment]
Thanks for raising the PR ☺️ we've had previous requests for supporting translation, so I wanted to check whether this change will prevent this in future? We would generally try to support new sphinx features rather than disable them

**Comment by mitya57** [comment]
I disables this feature only in tests, it won't be disabled for sphinx-tabs users.

When you decide to drop support for old Sphinx versions (< 7.1), you can revert this change and update the test expectations instead.

**Comment by foster999** [comment]
I think it would be best for the tests to reflect the latest sphinx version. We should be able to fix this by regenerating the regression tests under a normal test run

**Comment by mitya57** [comment]
But then the tests will fail with older Sphinx.

Although, I can put some `.replace()` in Python code to make it work with old Sphinx too. Will that work for you?

**Comment by mitya57** [comment]
I have implemented the approach from my last comment now.

**Review by Daltz333 — APPROVED** [review]
LGTM

**Pull request merged**
